- name: Install packages
  apt:
      update_cache: yes
      state: present
      pkg:
        - htop
        - iftop
        - tcpdump
        - mc
        - curl
        - telnet
        - netcat
        - net-tools
        - iptables
        - qrencode
